version: "3.8"

services:
  tomcat:
    image: docker.io/bitnami/tomcat:10.1
    ports:
      - "8080:8080"
    volumes:
      - "./code:/bitnami/tomcat/webapps/ROOT"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - TOMCAT_USERNAME=root
      - TOMCAT_PASSWORD=root
    depends_on:
      - mysql

  mysql:
    image: mysql:5
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3380:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
